#!/usr/bin/env python3

def p1():
    f = open("code.txt", "r")
    txt = f.read()
    str1= ""
    str2 = ""
    for i in range(0, len(txt)):
        if (len(str1) == 4):
            str1 = str1[1:]
        str1 += txt[i]
        str2 += txt[i]
        if i > 2:
            if (str1.count(str1[0]) == 1 and str1.count(str1[1]) == 1 and str1.count(str1[2]) == 1 and str1.count(str1[3]) == 1):
                print(len(str2))
                exit()

def p2():
    f = open("code.txt", "r")
    txt = f.read()
    str1= ""
    str2 = ""
    for i in range(0, len(txt)):
        if (len(str1) == 14):
            str1 = str1[1:]
        str1 += txt[i]
        str2 += txt[i]
        if i > 2:
            if (str1.count(str1[0]) == 1 and str1.count(str1[1]) == 1 and str1.count(str1[2]) == 1 and str1.count(str1[3]) == 1 and str1.count(str1[4]) == 1 and str1.count(str1[5]) == 1 and str1.count(str1[6]) == 1 and str1.count(str1[7]) == 1 and str1.count(str1[8]) == 1 and str1.count(str1[9]) == 1 and str1.count(str1[10]) == 1 and str1.count(str1[11]) == 1 and str1.count(str1[12]) == 1 and str1.count(str1[13]) == 1):
                print(len(str2))
                exit()

p2()
