#!/usr/bin/env python3

def p1():
    f = open("code.txt", "r")
    txt = f.read()
    rucksack = txt.split('\n')
    half = []
    str1=""
    str2=""
    for i in range(0, len(rucksack)):
        for d in range(0, len(rucksack[i])):
            if (d < len(rucksack[i])/2):
                str1 += rucksack[i][d]
            else:
                str2 += rucksack[i][d]
        half.append([str1, str2])
        str1=""
        str2=""
    chars = []
    for i in range(0, len(half)):
        for d in range(0, len(half[i][0])):
            if (half[i][0][d] in half[i][1]):
                chars.append(half[i][0][d])
                break
    nbr = 0
    for i in range(0, len(chars)):
        if(ord(chars[i]) < 96):
            nbr += ord(chars[i]) - 38
        else:
            nbr += (ord(chars[i]) - 96)
    print(nbr)
    return

def p2():
    f = open("code.txt", "r")
    txt = f.read()
    half = txt.split('\n')
    d=0
    tot = [[]]
    for i in range(0, len(half)):
        if (i % 3 == 0 and i != 0):
            tot.append([])
            d += 1
        tot[d].append(half[i])
    chars = []
    for i in range(0, len(tot)):
        for e in range(0, len(tot[i][0])):
            if (tot[i][0][e] in tot[i][1] and tot[i][0][e] in tot[i][2]):
                chars.append(tot[i][0][e])
                break
    nbr = 0
    for i in range(0, len(chars)):
        if(ord(chars[i]) < 96):
            nbr += ord(chars[i]) - 38
        else:
            nbr += (ord(chars[i]) - 96)
    print(nbr)
    return


p2()