#!/usr/bin/env python3

def parse(n):
    return eval(n)

def main():
    f = open("code.txt", "r")
    txt = f.read()
    totMonkeys = txt.split('\n\n')
    monkeys = []
    for i in range(0, len(totMonkeys)):
        monkeys.append(totMonkeys[i].split('\n'))
    tab = []
    for i in range(len(monkeys)):
        tab.append([])
        tab[i].append(list(map(parse, monkeys[i])))
    for i in tab:
        for d in i:
            for (e, f) in zip(d[0], d[1]):
                print(e, f)
main()
