#!/usr/bin/env python3

def main():
    f = open("code.txt", "r")
    txt = f.read()
    total = txt.split('\n')
    d = 0
    tab = [[]]
    for i in range(len(total)):
        if (total[i] == ''):
            tab.append([])
            d += 1
            continue
        tab[d].append(total[i])
    max = 0
    totMax = []
    for i in range(len(tab)):
        tot = 0
        for a in range(len(tab[i])):
            tot += int(tab[i][a])
            if (tot >= max):
                max = tot
        totMax.append(tot)
    totMax.sort()
    finalAnswer = totMax[len(totMax) - 1] + totMax[len(totMax) - 2] + totMax[len(totMax) - 3]
    print(totMax[len(totMax) - 1])
    print(finalAnswer)
    return

main()