#!/usr/bin/env python3

def main():
    f = open("code.txt", "r")
    txt = f.read()
    total = txt.split('\n')
    yes = []
    for i in range(len(total)):
        yes.append(total[i].split(' '))
    tot = 0
    for d in range(len(yes)):
        if (yes[d][0] == 'A'):
            if (yes[d][1] == 'X'):
                tot += (3+0)
            if (yes[d][1] == 'Y'):
                tot += (1+ 3)
            if (yes[d][1] == 'Z'):
                tot += (2+6)
        if (yes[d][0] == 'B'):
            if (yes[d][1] == 'X'):
                tot += (1+0)
            if (yes[d][1] == 'Y'):
                tot += (2+3)
            if (yes[d][1] == 'Z'):
                tot += (3+6)
        if (yes[d][0] == 'C'):
            if (yes[d][1] == 'X'):
                tot += (2+0)
            if (yes[d][1] == 'Y'):
                tot += (3+3)
            if (yes[d][1] == 'Z'):
                tot += (1+6)
    print(tot)
    return

main()