#!/usr/bin/env python3

def main():
    f = open("code.txt", "r")
    txt = f.read()
    x = txt.split("\n")
    a = []
    for i in range(0, len(x)):
        a.append(x[i].split(","))
    b = []
    for i in range(0, len(a)):
        str1 = a[i][0].split("-")
        str2 = a[i][1].split("-")
        b.append([str1, str2])
    tot = 0
    for t in range(0, len(b)):
        if (int(b[t][0][0]) >= int(b[t][1][0]) and int(b[t][0][1]) <= int(b[t][1][1])):
            print("1 : ", t)
            #print("2 dans 1 : ", t)
            tot += 1
        elif (int(b[t][1][0]) >= int(b[t][0][0]) and int(b[t][1][1]) <= int(b[t][0][1])):
            print("2 : ", t)
            #print("1 dans 2 : ", t)
            tot += 1
        elif (int(b[t][0][1]) >= int(b[t][1][0]) and int(b[t][0][0]) <= int(b[t][1][1])):
            print("3 : ", t)
            tot += 1
    print(tot)
    return

main()