#!/usr/bin/env python3

def p1():
    f = open("code.txt", "r")
    txt = f.read()
    map = txt.split('\n')
    visible = True
    total=0
    blocked=0
    for i in range(1, len(map)-1):
        for d in range(1, len(map[i])-1):
            for h in range(i-1, -1, -1):
                if (map[i][d] <= map[h][d]):
                    visible=False
                    break
            if (visible == False):
                visible=True
                for h in range(d+1, len(map[i])):
                    if (map[i][d] <= map[i][h]):
                        visible=False
                        break
                if (visible == False):
                    visible=True
                    for h in range(d-1, -1, -1):
                        if (map[i][d] <= map[i][h]):
                            visible=False
                            break
                    if (visible == False):
                        visible=True
                        for h in range(i+1, len(map)):
                            if (map[i][d] <= map[h][d]):
                                visible=False
                                break
                        if (visible == False):
                            visible=True
                        else:
                            total+=1
                    else:
                        total+=1
                else:
                    total+=1
            else:
                total+=1
    print(total+(len(map)*4) - 4)

def p2():
    f = open("code.txt", "r")
    txt = f.read()
    map = txt.split('\n')
    visibleTop = True
    visibleRight = True
    visibleLeft = True
    visibleBottom = True
    total=0
    blockedTop=0
    blockedBottom=0
    blockedRight=0
    blockedLeft=0
    max=0
    for i in range(0, len(map)):
        for d in range(0, len(map[i])):
            if i >= 1:
                for h in range(i-1, -1, -1):
                    visibleTop = True
                    if (map[i][d] <= map[h][d]):
                        blockedTop = (i-h)
                        visibleTop=False
                        break
                if (visibleTop == True):
                    blockedTop = i
            else:
                blockedTop = 0
            if d < len(map[i])-1:
                for h in range(d+1, len(map[i])):
                    visibleRight = True
                    if (map[i][d] <= map[i][h]):
                        blockedRight =h-d
                        visibleRight=False
                        break
                if (visibleRight == True):
                    blockedRight =(len(map[i])-d-1)
            else:
                blockedRight =0
            if d >= 1:
                for h in range(d-1, -1, -1):
                    visibleLeft = True
                    if (map[i][d] <= map[i][h]):
                        blockedLeft =(d-h)
                        visibleLeft=False
                        break
                if (visibleLeft == True):
                    blockedLeft=d
            else:
                blockedLeft =0
            if i < len(map)-1:
                for h in range(i+1, len(map)):
                    visibleBottom = True
                    if (map[i][d] <= map[h][d]):
                        blockedBottom = (h-i)
                        visibleBottom=False
                        break
                if (visibleBottom == True):
                    blockedBottom = len(map) - i - 1
            else:
                blockedBottom = 0
            if (blockedTop*blockedLeft*blockedRight*blockedBottom >= max):
                max = blockedTop*blockedLeft*blockedRight*blockedBottom
    print(max)

p2()
